steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-southeast1-docker.pkg.dev/innova-hack/credence/credence-opa:latest', '-f', 'opa.Dockerfile', '.']
images:
  - 'asia-southeast1-docker.pkg.dev/innova-hack/credence/credence-opa:latest'
