"use client";

import { useEffect, useRef, useState } from "react";
import { Send, X } from "lucide-react";

/**
 * The floating page assistant.
 *
 * A chat bubble on a fintech site is a place where a visitor reasonably expects
 * to ask "can I get credit" and "is my money safe", so two things are load
 * bearing here rather than decorative: the opening message says it answers only
 * about the page, and every reply carries a small label naming what produced it
 * — the model, or the page's own facts. A visitor who reads a sentence about
 * repayment order should be able to tell whether a language model wrote it.
 */

type Source = "canned" | "model" | "facts";
type Message = { role: "user" | "orb"; text: string; source?: Source };

const OPENING: Message = {
  role: "orb",
  text: "Hi — I'm the CredenceAI orb. Ask me about anything on this page: the vaults, the repayment order, the agent passport, or what's real and what's sandbox.",
  source: "canned",
};

const SUGGESTIONS = [
  "What is CredenceAI?",
  "How does repayment work?",
  "Is this real money?",
];

/** Which tier answered. Shown because "a model wrote this" and "this came from
 *  the page" are different levels of confidence and hiding the difference is
 *  the small dishonesty that makes chat widgets untrustworthy. */
const SOURCE_LABEL: Record<Source, string> = {
  canned: "scripted reply",
  model: "generated by a local model",
  facts: "from this page's stated facts",
};

export function Orb() {
  const [open, setOpen] = useState(false);
  const [messages, setMessages] = useState<Message[]>([OPENING]);
  const [draft, setDraft] = useState("");
  const [pending, setPending] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: "smooth" });
  }, [messages, pending]);

  useEffect(() => {
    if (open) inputRef.current?.focus();
  }, [open]);

  // Escape closes the panel. It covers the page content, so leaving the only
  // exit as a small button is a trap for anyone not using a mouse.
  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") setOpen(false);
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [open]);

  async function send(text: string) {
    const question = text.trim();
    if (question === "" || pending) return;

    setMessages((prev) => [...prev, { role: "user", text: question }]);
    setDraft("");
    setPending(true);

    try {
      const res = await fetch("/api/orb", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ message: question }),
      });
      const data = (await res.json()) as { reply?: string; source?: Source };
      setMessages((prev) => [
        ...prev,
        {
          role: "orb",
          text: data.reply ?? "Something went wrong on my end. Try again?",
          source: data.source ?? "facts",
        },
      ]);
    } catch {
      setMessages((prev) => [
        ...prev,
        {
          role: "orb",
          text: "I couldn't reach my own service just then. The page itself is unaffected — try me again in a moment.",
          source: "facts",
        },
      ]);
    } finally {
      setPending(false);
    }
  }

  return (
    <>
      {open && (
        <div
          role="dialog"
          aria-label="CredenceAI page assistant"
          className="fixed bottom-24 right-5 z-50 flex h-[min(30rem,calc(100dvh-8rem))] w-[min(23rem,calc(100vw-2.5rem))] flex-col overflow-hidden rounded-2xl border border-neutral-200 bg-white shadow-2xl sm:right-6"
        >
          <header className="flex items-center justify-between border-b border-neutral-100 px-4 py-3">
            <div className="flex items-center gap-2.5">
              <span className="relative flex h-2.5 w-2.5">
                <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-accent-strong opacity-60" />
                <span className="relative inline-flex h-2.5 w-2.5 rounded-full bg-accent-strong" />
              </span>
              <div>
                <p className="text-sm font-semibold text-ink">CredenceAI orb</p>
                <p className="text-[0.7rem] text-neutral-500">Answers about this page only</p>
              </div>
            </div>
            <button
              onClick={() => setOpen(false)}
              aria-label="Close assistant"
              className="rounded-lg p-1.5 text-neutral-400 transition hover:bg-neutral-100 hover:text-ink"
            >
              <X className="h-4 w-4" />
            </button>
          </header>

          <div ref={scrollRef} className="flex-1 space-y-3 overflow-y-auto px-4 py-4">
            {messages.map((m, i) => (
              <div key={i} className={m.role === "user" ? "flex justify-end" : ""}>
                <div
                  className={
                    m.role === "user"
                      ? "max-w-[85%] rounded-2xl rounded-br-sm bg-ink px-3.5 py-2 text-sm leading-relaxed text-white"
                      : "max-w-[92%] rounded-2xl rounded-bl-sm bg-neutral-100 px-3.5 py-2 text-sm leading-relaxed text-neutral-800"
                  }
                >
                  {m.text}
                  {m.role === "orb" && m.source !== undefined && (
                    <span className="mt-1.5 block text-[0.65rem] uppercase tracking-wide text-neutral-500">
                      {SOURCE_LABEL[m.source]}
                    </span>
                  )}
                </div>
              </div>
            ))}

            {pending && (
              <div className="flex gap-1 px-1 py-1" aria-label="Thinking">
                {[0, 150, 300].map((delay) => (
                  <span
                    key={delay}
                    className="h-1.5 w-1.5 animate-bounce rounded-full bg-neutral-400"
                    style={{ animationDelay: `${delay}ms` }}
                  />
                ))}
              </div>
            )}

            {messages.length === 1 && !pending && (
              <div className="flex flex-wrap gap-1.5 pt-1">
                {SUGGESTIONS.map((s) => (
                  <button
                    key={s}
                    onClick={() => void send(s)}
                    className="rounded-full border border-neutral-200 px-2.5 py-1 text-xs text-neutral-600 transition hover:border-neutral-300 hover:bg-neutral-50"
                  >
                    {s}
                  </button>
                ))}
              </div>
            )}
          </div>

          <form
            onSubmit={(e) => {
              e.preventDefault();
              void send(draft);
            }}
            className="flex items-center gap-2 border-t border-neutral-100 px-3 py-2.5"
          >
            <input
              ref={inputRef}
              value={draft}
              onChange={(e) => setDraft(e.target.value)}
              maxLength={600}
              placeholder="Ask about this page…"
              aria-label="Your question"
              className="min-w-0 flex-1 bg-transparent px-1 text-sm text-ink outline-none placeholder:text-neutral-400"
            />
            <button
              type="submit"
              disabled={pending || draft.trim() === ""}
              aria-label="Send"
              className="rounded-lg bg-ink p-2 text-white transition disabled:opacity-30"
            >
              <Send className="h-3.5 w-3.5" />
            </button>
          </form>
        </div>
      )}

      <button
        onClick={() => setOpen((v) => !v)}
        aria-label={open ? "Close assistant" : "Open assistant"}
        aria-expanded={open}
        className="fixed bottom-5 right-5 z-50 flex h-14 w-14 items-center justify-center rounded-full bg-ink shadow-xl transition hover:scale-105 active:scale-95 sm:right-6"
      >
        {open ? (
          <X className="h-5 w-5 text-white" />
        ) : (
          <span className="relative flex h-6 w-6">
            <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-accent-strong opacity-40" />
            <span className="relative inline-flex h-6 w-6 rounded-full bg-gradient-to-br from-accent to-accent-strong" />
          </span>
        )}
      </button>
    </>
  );
}
